Fix SIGUNUSED as the signal is deprecated since glibc 2.26
If glibc version >= 2.26, SIGUNUSED is not available and hence
build fails with following.
build_ipc.c:59:17: error: ‘SIGUNUSED’ undeclared (first use in
this function); did you mean ‘SI_USER’?
 #define SIGSYS (SIGUNUSED)
This patch fixes defines if it is not defined

Signed-off-by: Harish <harish@linux.vnet.ibm.com>